### ISSUE TITLE
typescript defekt und läßt sich nicht reparieren

### ISSUE THREAD

**Issue by SoerenR82** [buanet/docker-iobroker#109]
Mein typescrupt ist defekt und es läßt sich nicht reparieren.

 `2020-06-08 15:20:54.446 - error: host.iobroker Caught by controller[0]: internal/modules/cjs/loader.js:969
2020-06-08 15:20:54.447 - error: host.iobroker Caught by controller[0]: throw err;
2020-06-08 15:20:54.447 - error: host.iobroker Caught by controller[0]: ^
2020-06-08 15:20:54.447 - error: host.iobroker Caught by controller[0]: Error: Cannot find module 'typescript'
2020-06-08 15:20:54.448 - error: host.iobroker Caught by controller[0]: Require stack:
2020-06-08 15:20:54.448 - error: host.iobroker Caught by controller[0]: - /opt/iobroker/node_modules/virtual-tsc/build/compiler.js
2020-06-08 15:20:54.449 - error: host.iobroker Caught by controller[0]: - /opt/iobroker/node_modules/virtual-tsc/build/index.js
2020-06-08 15:20:54.449 - error: host.iobroker Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.javascript/main.js
2020-06-08 15:20:54.449 - error: host.iobroker Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
2020-06-08 15:20:54.449 - error: host.iobroker Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:842:27)
2020-06-08 15:20:54.450 - error: host.iobroker Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-06-08 15:20:54.450 - error: host.iobroker Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
2020-06-08 15:20:54.450 - error: host.iobroker Caught by controller[0]: at Object. (/opt/iobroker/node_modules/virtual-tsc/build/compiler.js:3:10)
2020-06-08 15:20:54.450 - error: host.iobroker Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-06-08 15:20:54.451 - error: host.iobroker Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-06-08 15:20:54.451 - error: host.iobroker Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
2020-06-08 15:20:54.451 - error: host.iobroker Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2020-06-08 15:20:54.451 - error: host.iobroker Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-06-08 15:20:54.451 - error: host.iobroker Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
2020-06-08 15:20:54.452 - error: host.iobroker Caught by controller[0]: at Object. (/opt/iobroker/node_modules/virtual-tsc/build/index.js:3:18)
2020-06-08 15:20:54.452 - error: host.iobroker Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-06-08 15:20:54.452 - error: host.iobroker Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-06-08 15:20:54.452 - error: host.iobroker Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
2020-06-08 15:20:54.452 - error: host.iobroker Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2020-06-08 15:20:54.453 - error: host.iobroker Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-06-08 15:20:54.453 - error: host.iobroker Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
2020-06-08 15:20:54.453 - error: host.iobroker Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.javascript/main.js:35:24)
2020-06-08 15:20:54.453 - error: host.iobroker Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-06-08 15:20:54.453 - error: host.iobroker Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-06-08 15:20:54.453 - error: host.iobroker Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
2020-06-08 15:20:54.454 - error: host.iobroker Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2020-06-08 15:20:54.454 - error: host.iobroker Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2020-06-08 15:20:54.454 - error: host.iobroker Caught by controller[0]: at internal/main/run_main_module.js:17:47
2020-06-08 15:20:54.454 - error: host.iobroker Caught by controller[0]: {
2020-06-08 15:20:54.454 - error: host.iobroker Caught by controller[0]: code: 'MODULE_NOT_FOUND',
2020-06-08 15:20:54.455 - error: host.iobroker Caught by controller[0]: requireStack: [
2020-06-08 15:20:54.455 - error: host.iobroker Caught by controller[0]: '/opt/iobroker/node_modules/virtual-tsc/build/compiler.js',
2020-06-08 15:20:54.455 - error: host.iobroker Caught by controller[0]: '/opt/iobroker/node_modules/virtual-tsc/build/index.js',
2020-06-08 15:20:54.455 - error: host.iobroker Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.javascript/main.js'
2020-06-08 15:20:54.455 - error: host.iobroker Caught by controller[0]: ]
2020-06-08 15:20:54.456 - error: host.iobroker Caught by controller[0]: }
2020-06-08 15:20:54.456 - error: host.iobroker instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)`

bei dem versuch das ganze zu reparieren kommt nur das bei raus.

 `which nodejs && nodejs -v && which node && node -v && which npm && npm -v && apt policy nodejs`

`/usr/bin/nodejs
--
  | v12.18.0
  | /usr/bin/node
  | v12.18.0
  | /usr/bin/npm
  | sudo: Hostname iobroker kann nicht aufgelöst werden
  | sudo: Die Audit-Nachricht kann nicht gesendet werden: Unbekannter Fehler -1
  | sudo: pam_open_session: Systemfehler
  | sudo: Regelwerks-Plugin konnte Sitzung nicht initialisieren
`

`cd /opt/iobroker/node_modules/iobroker.javascript
npm install --production
`

`root@iobroker2:/opt/iobroker/node_modules/iobroker.javascript# npm install --production
--
  | npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
  | npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
  | npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  | npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
  | npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  | npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/@types
  | npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules
  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/mocha/node_modules/chokidar/node_modules/fsevents):
  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
  |  
  | npm ERR! code EACCES
  | npm ERR! syscall access
  | npm ERR! path /opt/iobroker/node_modules/iobroker.javascript/node_modules/@types
  | npm ERR! errno -13
  | npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules/@types'
  | npm ERR!  { [Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules/@types']
  | npm ERR!   stack:
  | npm ERR!    'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.javascript/node_modules/@types\'',
  | npm ERR!   errno: -13,
  | npm ERR!   code: 'EACCES',
  | npm ERR!   syscall: 'access',
  | npm ERR!   path:
  | npm ERR!    '/opt/iobroker/node_modules/iobroker.javascript/node_modules/@types' }
  | npm ERR!
  | npm ERR! The operation was rejected by your operating system.
  | npm ERR! It is likely you do not have the permissions to access this file as the current user
  | npm ERR!
  | npm ERR! If you believe this might be a permissions issue, please double-check the
  | npm ERR! permissions of the file and its containing directories, or try running
  | npm ERR! the command again as root/Administrator.
  |  
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /opt/iobroker/.npm/_logs/2020-06-08T17_54_10_994Z-debug.log
`

Ich hab mir [https://forum.iobroker.net/topic/34206/nach-scriptausführung-nur-noch-fehler-und-keine-funkion/11](url) hier schon versucht Hilfe zu holen. Allerdings hat das ganze nur bedingt funktioniert. Ich hatte sowohl das Problem auf dem Pi3 als auch auf der Synology DS415+ im Docker. Auf dem Pi war das ganze erfolgreich. Bei der Docker Instanz ist das ganze alleinig nicht von erfolg gekrönt.

**Comment by buanet** [comment]
Hallo,
leider fehlen wichtige Details. 
Anhand der Meldungen errate ich jetzt einfach mal, dass du deinen Container mit dem Host Netzwerk verwendest? 
Falls dem so ist, läuft du hier in einen bekannten Bug auf Synology Systemen. Schuld ist ein veralteter Kernel im DSM der es verhindert, dass du in einem Docker Container mit Host Netzwerk sudo verwenden kannst. Leider wird sudo jedoch in vielen Scripten verwendet...

Das kannst du umgehen, indem du deinen ioBroker Ordner temporär in einen Container einhängst, der im Bridge Netzwerk läuft. Dann deine Kommandos ausführen (es empfiehlt sich z.B. auch ein npm rebuild) und anschließend wieder auf einen Container mit Host Netzwerk wechseln.

Vorher das Backup deines ioBroker Verzeichnisses nicht vergessen!

Was ich generell empfehlen würde, wenn npm & co nicht mehr wollen: 
* ioBroker Backup erstellen (z.B. mit BackitUp Adapter)
* Backupfile in einen leeren Ordner Kopieren
* Neuen Container einrichten (nach Möglichkeit mit der aktuellen Beta Version des Images)
* das Verzeichnis mit dem Backupfile dort als "opt/iobroker" mounten

Das Startupscript installiert dann iobroker neu und stellt das Backup wieder her. Dann sollten alle npm Pakete wieder aktuell sein... Ebenso wie Node und npm selbst...
