### ISSUE TITLE
cant install xbox adapter

### ISSUE THREAD

**Issue by Reislord** [buanet/docker-iobroker#125]
I tryed to install the xbox adapter in my docker-composed buanet/iobroker container and got the following error:

$ ./iobroker add xbox  --host iobroker
NPM version: 6.14.5
npm install iobroker.xbox@0.6.5 --loglevel error --unsafe-perm --prefix "/opt/iobroker" (System call)
Traceback (most recent call last):  File "/opt/iobroker/node_modules/nopy/src/get-pip.py", line 20061, in <module>    main()  File "/opt/iobroker/node_modules/nopy/src/get-pip.py", line 194, in main    bootstrap(tmpdir=tmpdir)  File "/opt/iobroker/node_modules/nopy/src/get-pip.py", line 82, in bootstrap    import pip  File "/tmp/tmpbhl12sq0/pip.zip/pip/__init__.py", line 26, in <module>  File "/tmp/tmpbhl12sq0/pip.zip/pip/utils/__init__.py", line 23, in <module>  File "/tmp/tmpbhl12sq0/pip.zip/pip/locations.py", line 9, in <module>ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.7/distutils/__init__.py)
Error: Exited with code 1.    at ChildProcess.<anonymous> (/opt/iobroker/node_modules/nopy/src/api.js:277:20)    at ChildProcess.emit (events.js:315:20)    at maybeClose (internal/child_process.js:1021:16)    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm
 ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! iobroker.xbox@0.6.5 install: `npip install`npm ERR! Exit status 1npm 
ERR! npm ERR! Failed at the iobroker.xbox@0.6.5 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     /opt/iobroker/.npm/_logs/2020-07-07T19_40_19_495Z-debug.log
ERROR: host.iobroker Cannot install iobroker.xbox@0.6.5: 1
ERROR: process exited with code 25

is there a workaround to fix it to communicate with my xbox

**Comment by buanet** [comment]
Did you read the readme.md of the adapter? Did you fulfill the requirements? Did you read the mentioned debug log  (/opt/iobroker/.npm/_logs/2020-07-07T19_40_19_495Z-debug.log) Did you consult iobroker forum or open an issue at the adapter site? Why do you think this is caused by the Docker image? What a workaround do you expect?

For me this is not related to the container at the moment. Seems that the adapter is simply not installed successfully...

Regards,
André

**Comment by buanet** [comment]
No response for two weeks now. This issue will be closed.

Regards,
André
