### ISSUE TITLE
Restor not possible

### ISSUE THREAD

**Issue by DocUltra** [buanet/docker-iobroker#138]
The restore will not be executed.
pls. see the restore.log

`internal/fs/utils.js:269
    throw err;
    ^

Error: EACCES: permission denied, scandir '/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/../../../../backups/'
    at Object.readdirSync (fs.js:955:3)
    at BackupRestore.listBackups (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:682:30)
    at BackupRestore.restoreBackup (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:862:28)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:783:24
    at Object.connected (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2511:41)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemServerRedis.js:72:46)
    at processImmediate (internal/timers.js:461:21) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/../../../../backups/'
}`

**Comment by DocUltra** [comment]
Is the problem maybe the GID or UID?

**Comment by buanet** [comment]
I'm not sure. But definitely looks like a permission issue.
Find out the GID/ UID of a"normal" user and set him to own the directory and the backup file. 

As you did not post any config, hopefully volume mount is configured correctly?

BTW, did you read this in readme.md?
`Important: If the folder you mount to /opt/iobroker in your container is placed on a mounted device, partition or other storage, the mountpoint on your host should NOT have the "noexec" flag activated. Otherwise you may get problems executing ioBroker inside the container!`

Regards,
André

**Comment by buanet** [comment]
No further details provided. I'll close this issue.
