### ISSUE TITLE
gyp ERR! build error | authenticate-pamgyp ERR! |   beim  up- oder downgrade eines Adapters

### ISSUE THREAD

**Issue by DIY-Gidi** [buanet/docker-iobroker#149]
Hallo,
**ich möchte mich zuerst bei Euch bedanken, dass Ihr es ermöglicht vielen Laien zu so tollen Programmierungen Zugang zu erhalten.**
Bin von Pi2 auf Synology/Docker umgezogen. Nach ein paar "Startschwierigkeiten" laufen alle Adapter einwandfrei.
**Nur**, wenn ich einen Adapter update bekomme ich diese Meldungen im Log. 

```
$ ./iobroker upgrade backitup
Update backitup from @1.6.6 to @1.7.0
NPM version: 6.14.8
npm install iobroker.backitup@1.7.0 --loglevel error --prefix "/opt/iobroker" (System call)
In file included from ../authenticate_pam.cc:23:../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)                                                              ^
../authenticate_pam.cc: In function ‘void after_doing_auth(uv_work_t*, int)’:../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);                                                                                       ^
In file included from ../authenticate_pam.cc:23:../../nan/nan.h:1026:46: note: declared here   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(                                              ^~~~~~~~~~~~../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);                                                                                       ^In file included from ../authenticate_pam.cc:23:../../nan/nan.h:1026:46: note: declared here   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(                                              ^~~~~~~~~~~~
../authenticate_pam.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Authenticate(Nan::NAN_METHOD_ARGS_TYPE)’:../authenticate_pam.cc:147:83: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]   Local<Value> res = options->Get(Nan::New<String>("serviceName").ToLocalChecked());                                                                                   ^In file included from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14,                 from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:27,                 from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:3553:51: note: declared here   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));                                                   ^~~/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../authenticate_pam.cc:150:69: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], long unsigned int)’    serviceName->WriteUtf8(m->serviceName, sizeof(m->serviceName) - 1);                                                                     ^In file included from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,       ^~~~~~~~~/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:152:69: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]   res = options->Get(Nan::New<String>("remoteHost").ToLocalChecked());                                                                     ^In file included from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14,                 from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:27,                 from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:3553:51: note: declared here   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));                                                   ^~~/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../authenticate_pam.cc:155:66: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], long unsigned int)’    remoteHost->WriteUtf8(m->remoteHost, sizeof(m->remoteHost) - 1);                                                                  ^In file included from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,       ^~~~~~~~~/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:160:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], long unsigned int)’  username->WriteUtf8(m->username, sizeof(m->username) - 1);                                                          ^In file included from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,       ^~~~~~~~~/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:161:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], long unsigned int)’  password->WriteUtf8(m->password, sizeof(m->password) - 1);                                                          ^In file included from /opt/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,       ^~~~~~~~~/opt/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc: At global scope:../authenticate_pam.cc:170:11: error: variable or field ‘init’ declared void void init(Handle<Object> exports) {           ^~~~~~../authenticate_pam.cc:170:11: error: ‘Handle’ was not declared in this scope
../authenticate_pam.cc:170:11: note: suggested alternative: ‘rand_r’ void init(Handle<Object> exports) {           ^~~~~~           rand_r../authenticate_pam.cc:170:24: error: expected primary-expression before ‘>’ token void init(Handle<Object> exports) {                        ^../authenticate_pam.cc:170:26: error: ‘exports’ was not declared in this scope void init(Handle<Object> exports) {                          ^~~~~~~In file included from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:../authenticate_pam.cc:175:31: error: ‘init’ was not declared in this scope NODE_MODULE(authenticate_pam, init);                               ^~~~/opt/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:727:36: note: in definition of macro ‘NODE_MODULE_X’       (node::addon_register_func) (regfunc),                          \                                    ^~~~~~~../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(authenticate_pam, init); ^~~~~~~~~~~
../authenticate_pam.cc:175:31: note: suggested alternative: ‘int’ NODE_MODULE(authenticate_pam, init);                               ^~~~/opt/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:727:36: note: in definition of macro ‘NODE_MODULE_X’       (node::addon_register_func) (regfunc),                          \                                    ^~~~~~~../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(authenticate_pam, init); ^~~~~~~~~~~
make: *** [authenticate_pam.target.mk:111: Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack     at ChildProcess.emit (events.js:314:20)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)gyp ERR! System Linux 4.4.59+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pamgyp ERR! node -v v12.19.0gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
upload [3] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/words.js words.js application/javascript
Update "system.adapter.backitup.0"
upload [2] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index_m.html index_m.html text/html
upload [1] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index.html index.html text/html
upload [0] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/backitup.png backitup.png image/png
Adapter "backitup" updated
process exited with code 0
```

Wie schon erwähnt. Adapter laufen, werden auch upgedated. Nur eben der Fehler mit "authenticat pam". Kann mir bitte jemand helfen? Vielen Dank!

**Comment by buanet** [comment]
Hallo,
das ist ein alter Hut. hat nichts mit dem ioBroker Container zu tun.
Im Forum findest du massig Infos dazu. Wenn dein Install durch läuft, dann kannst du das ignorieren. 

https://forum.iobroker.net/topic/38459/gel%C3%B6st-warn-bei-allen-adapter-neu-inst-authenticate_pam

Wenn das deine Frage beantwortet, schließe bitte den Issue. Danke.

MfG,
André

**Comment by DIY-Gidi** [comment]
Danke,
soviel ich auf die Schnelle verstanden habe, liegt das am Terminaladapter. Brauche ich sowieso nicht. Teste ich, wenn ich zu Hause bin. Sonst habe ich ja jetzt wieder was zum Lesen gefunden. :-) 
Vielen Dank!
LG
Ewald
