### ISSUE TITLE
sql-adapter (v 1.9.5) not starting

### ISSUE THREAD

**Issue by jomjol** [buanet/docker-iobroker#62]
With update of my iobroker-docker to v4.0.0 the sql-adapter does not start anymore with the following error message:
```
2020-01-06 15:58:07.231  - info: host.iobroker instance system.adapter.sql.0 started with pid 848
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: The module '/opt/iobroker/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/mmmagic/lib/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

With Version 3.1.0 the sql-adapter ist working without any problems.

Any hints?

**Comment by buanet** [comment]
Seriously?
Please read the readme:
https://github.com/buanet/docker-iobroker/blob/master/README.md
And then the error message again...

Regards,
André
