### ISSUE TITLE
install adapter mihome-vacuum fails

### ISSUE THREAD

**Issue by ts617284** [buanet/docker-iobroker#91]
Hi andré, thanks for the great image!

I am trying to install/upgrade iobroker adapter mihome-vacuum (https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum):
installation routine fails:
`$ ./iobroker upgrade mihome-vacuum
Update mihome-vacuum from @1.1.5 to @2.0.7
NPM version: 6.13.4
npm install iobroker.mihome-vacuum@2.0.7 --loglevel error --prefix "/opt/iobroker" (System call)
gyp
 ERR! configure error gyp ERR! stack Error: write EPROTO 140440310937408:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:gyp ERR! stack gyp ERR! stack     at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)gyp ERR! System Linux 4.14.24-qnapgyp ERR! 
command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v10.19.0gyp ERR!
 node-gyp -v v5.0.5gyp ERR! not ok 
node-pre-gyp
 ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)node-pre-gyp 
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)node-pre-gyp ERR! System Linux 4.14.24-qnap
node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvasnode-pre-gyp ERR! node -v v10.19.0node-pre-gyp ERR! 
node-pre-gyp -v v0.11.0node-pre-gyp ERR! not ok 
npm
 ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the canvas@2.6.1 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     /opt/iobroker/.npm/_logs/2020-04-12T11_43_21_011Z-debug.log
ERROR: host.ioBroker-Host Cannot install iobroker.mihome-vacuum@2.0.7: 1
ERROR: process exited with code 25`

(sorry for bad log structure, unfortunatelly line brakes get not recognized when pasting?)

There is a post at github of mihome-vacuum which states to manually install canvas via "sudo npm install canvas --unsafe-perm=true", but that fails as well.

Happy to provide additional info!

Thanks a lot for your work!
Tim

**Comment by ts617284** [comment]
updated to newest buanet/iobroker image , updated a lot of adapters in the last days (admin, web, javascript,...) and now i can install the mihome-vacuum adapter.
Unfortunatelly I don't exactly know what solved it.
