### ISSUE TITLE
update to new version - error

### ISSUE THREAD

**Issue by Surfer2010** [buanet/docker-iobroker#98]
Hello, i pulled the new image today and restarted the container with the new image.
iobroker works again, all fine, but

1.) iobroker stop   (does not work)
2.) since the adapter view tells me "no compatible version of js-controller, must be >= 2.0.0" i thought i have to run  "npm rebuild" and also "tried npm install ioBroker/ioBroker.js-controller"
result have been some errors

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'ioBroker/ioBroker.js-controlle' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose config Skipping project config: /opt/iobroker/.npmrc. (matches userconfig)
5 verbose npm-session df5f9ea78cdadcd4
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for github:ioBroker/ioBroker.js-controlle Error while executing:
8 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t ssh://git@github.com/ioBroker/ioBroker.js-controlle.git
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
8 silly fetchPackageMetaData git@github.com: Permission denied (publickey).
8 silly fetchPackageMetaData fatal: Konnte nicht vom Remote-Repository lesen.
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
8 silly fetchPackageMetaData und das Repository existiert.
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData exited with error code: 128
9 timing stage:rollbackFailedOptional Completed in 4ms
10 timing stage:runTopLevelLifecycles Completed in 24052ms
11 verbose stack Error: exited with error code: 128
11 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12$
11 verbose stack     at ChildProcess.emit (events.js:198:13)
11 verbose stack     at maybeClose (internal/child_process.js:982:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
12 verbose cwd /opt/iobroker
13 verbose Linux 4.19.0-0.bpo.5-amd64
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "ioBroker/ioBroker.js-controlle"
15 verbose node v10.20.1
16 verbose npm  v6.14.4
17 error Error while executing:
17 error /usr/bin/git ls-remote -h -t ssh://git@github.com/ioBroker/ioBroker.js-controlle.git
17 error
17 error Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
17 error git@github.com: Permission denied (publickey).
17 error fatal: Konnte nicht vom Remote-Repository lesen.
17 error
17 error Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
17 error und das Repository existiert.
17 error
17 error exited with error code: 128
18 verbose exit [ 1, true ]
`

**Comment by Surfer2010** [comment]
closed :-) 

the solution was:
curl -sL https://iobroker.net/fix.sh | bash -
